In [1]:
import numpy as np

In [2]:
array2 = np.array([[2,4,6],[1,3,5],[22,23,34],[13,15,19]])
array2

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 34],
       [13, 15, 19]])

In [3]:
array2.ndim

2

In [4]:
array2[0]

array([2, 4, 6])

In [5]:
array2[2]

array([22, 23, 34])

In [6]:
array2[-2]

array([22, 23, 34])

In [7]:
array2[3,0]

13

In [8]:
array2[:2,1:]

array([[4, 6],
       [3, 5]])

In [9]:
array2[:2,:2]

array([[2, 4],
       [1, 3]])

In [11]:
array2[:,1]

array([ 4,  3, 23, 15])

In [13]:
array2[:2,:2] = 9

In [14]:
array2

array([[ 9,  9,  6],
       [ 9,  9,  5],
       [22, 23, 34],
       [13, 15, 19]])